-- simAssimp lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simAssimp=require('simAssimp')

function simAssimp.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simAssimp'][funcName]=wrapperGenerator(_G['simAssimp'][funcName])
    end

    wrapFunc('importShapesDlg',function(origFunc)
        return function(...)
            local filename=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            local _rets={origFunc(filename)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('exportShapesDlg',function(origFunc)
        return function(...)
            local filename,shapeHandles=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='table',item_type='int'},
                },
                ...
            )
            local _rets={origFunc(filename,shapeHandles)}
            return table.unpack(_rets)
        end
    end)

    simAssimp.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simAssimp.__addTypeCheck',true)

return simAssimp
