-- simICP lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simICP=require('simICP')

function simICP.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simICP'][funcName]=wrapperGenerator(_G['simICP'][funcName])
    end

    simICP.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simICP.__addTypeCheck',true)

return simICP
