-- simIM lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simIM=require('simIM')

function simIM.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simIM'][funcName]=wrapperGenerator(_G['simIM'][funcName])
    end

    wrapFunc('dataURL',function(origFunc)
        return function(...)
            local imgHandle,format=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string',default='BMP'},
                },
                ...
            )
            local _rets={origFunc(imgHandle,format)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('getMarkerBitSize',function(origFunc)
        return function(...)
            local dictType=checkargsEx(
                {level=1},
                {
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(dictType)}
            return table.unpack(_rets)
        end
    end)

    simIM.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simIM.__addTypeCheck',true)

return simIM
