-- simLDraw lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simLDraw=require('simLDraw')

function simLDraw.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simLDraw'][funcName]=wrapperGenerator(_G['simLDraw'][funcName])
    end

    simLDraw.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simLDraw.__addTypeCheck',true)

return simLDraw
