-- simQML lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simQML=require('simQML')

function simQML.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simQML'][funcName]=wrapperGenerator(_G['simQML'][funcName])
    end

    wrapFunc('sendEvent',function(origFunc)
        return function(...)
            local engine,name,data=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string'},
                    {type='table'},
                },
                ...
            )
            local _rets={origFunc(engine,name,data)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('setEventHandler',function(origFunc)
        return function(...)
            local engine,funcName=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string'},
                },
                ...
            )
            local _rets={origFunc(engine,funcName)}
            return table.unpack(_rets)
        end
    end)

    simQML.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simQML.__addTypeCheck',true)

return simQML
