-- simROS2 lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simROS2=require('simROS2')

function simROS2.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simROS2'][funcName]=wrapperGenerator(_G['simROS2'][funcName])
    end

    wrapFunc('timeFromFloat',function(origFunc)
        return function(...)
            local t=checkargsEx(
                {level=1},
                {
                    {type='float'},
                },
                ...
            )
            local _rets={origFunc(t)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('timeToFloat',function(origFunc)
        return function(...)
            local t=checkargsEx(
                {level=1},
                {
                    {type='table'},
                },
                ...
            )
            local _rets={origFunc(t)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('getSystemTime',function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets={origFunc()}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('getSimulationTime',function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets={origFunc()}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('importInterface',function(origFunc)
        return function(...)
            local name=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            local _rets={origFunc(name)}
            return table.unpack(_rets)
        end
    end)

    simROS2.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simROS2.__addTypeCheck',true)

return simROS2
