-- simSurfRec lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simSurfRec=require('simSurfRec')

function simSurfRec.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simSurfRec'][funcName]=wrapperGenerator(_G['simSurfRec'][funcName])
    end

    simSurfRec.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simSurfRec.__addTypeCheck',true)

return simSurfRec
