-- simUI lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simUI=require('simUI')

function simUI.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simUI'][funcName]=wrapperGenerator(_G['simUI'][funcName])
    end

    wrapFunc('insertTableRow',function(origFunc)
        return function(...)
            local ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(ui,widget,index)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('removeTableRow',function(origFunc)
        return function(...)
            local ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(ui,widget,index)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('insertTableColumn',function(origFunc)
        return function(...)
            local ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(ui,widget,index)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('removeTableColumn',function(origFunc)
        return function(...)
            local ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(ui,widget,index)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('setScene3DNodeParam',function(origFunc)
        return function(...)
            local ui,widget,nodeId,paramName,paramValue=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                    {type='string'},
                    {type='any'},
                },
                ...
            )
            local _rets={origFunc(ui,widget,nodeId,paramName,paramValue)}
            return table.unpack(_rets)
        end
    end)

    simUI.__addTypeCheck=nil
end

sim.registerScriptFuncHook('sysCall_init','simUI.__addTypeCheck',true)

return simUI
